development:
  adapter: postgresql
  encoding: unicode
  database: harold_development
  pool: 5
  username: mikekavouras
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: harold_test
  pool: 5
  username: mikekavouras
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: harold_production
  pool: 5
  username: harold
  password:
